#!/usr/bin/env bash

export KLAY_HOME="$HOME/.klay"
LOGS_DIR="$KLAY_HOME/logs"
if ! [ -d "$LOGS_DIR" ]; then
  mkdir -p "$LOGS_DIR"
fi

KLAY_PROCESSES="$KLAY_HOME/processes"

PROCESSES_DIR="$KLAY_HOME/processes.d"
if ! [ -d "$PROCESSES_DIR" ]; then
  mkdir -p "$PROCESSES_DIR"
fi

# klay -d start ...
# klay -d run ...

DETACH=$([[ "$1" == "-d" ]] || [[ "$1" == "--detach" ]] && echo -n 'y' || echo -n 'n')

# TODO:
# $DEBUG_OPTS

if ! [ -f /proc/sys/kernel/random/uuid  ]; then
  echo 'ERROR: path /proc/sys/kernel/random/uuid not found.' >&2
  exit 5
fi
EXTERNAL_ID=$(cat /proc/sys/kernel/random/uuid)
PROCESS_DIR="$PROCESSES_DIR/$EXTERNAL_ID"
mkdir -p "$PROCESS_DIR"

if ! [ -x "$(command -v nohup)" ]; then
  echo 'ERROR: nohup is not installed.' >&2
  exit 5
fi

if [ "$DETACH" == "n" ]; then
  # KLAY ID     LINUX PID    TYPE   VERSION    CREATED    STATUS    PORTS   ARGS
  echo "$EXTERNAL_ID;cat '$PROCESS_DIR/pid';cat '$PROCESS_DIR/type';cat '$PROCESS_DIR/version';$(date +"%Y-%m-%d %H:%M:%S");bash psw.sh $LINUX_PID;cat '$PROCESS_DIR/ports';'$@'" >> $KLAY_PROCESSES

  echo "$@"
  java $JAVA_OPTS -jar $JAR_LOCATION --external-id=${EXTERNAL_ID} "$@"
else
  # TODO:
  nohup java $JAVA_OPTS -jar $JAR_LOCATION --external-id=${EXTERNAL_ID} "$@" >> "${LOGS_DIR}/${EXTERNAL_ID}.log" 2> "${LOGS_DIR}/${EXTERNAL_ID}-errors.log" &
  LINUX_PID=$!
  echo 'Process started'
  echo "   Klay ID..: $EXTERNAL_ID"
  echo "   Linux pID: $LINUX_PID"

  # TODO: Add process info to list with 'klay ps'
  # KLAY ID     LINUX PID    TYPE   VERSION    CREATED    STATUS    PORTS   ARGS
  echo "$EXTERNAL_ID;$LINUX_PID;cat '$PROCESS_DIR/type';cat '$PROCESS_DIR/version';$(date +"%Y-%m-%d %H:%M:%S");bash psw.sh $LINUX_PID;cat '$PROCESS_DIR/ports';'$@'" >> $KLAY_PROCESSES

  # TYPE, VERSION and PORTS are written by the processes it self
fi
