#!/usr/bin/env bash

SCRIPTS_HOME=$(dirname "$0")

export KLAY_HOME="$HOME/.klay"
LOGS_DIR="$KLAY_HOME/logs"
if ! [ -d "$LOGS_DIR" ]; then
  mkdir -p "$LOGS_DIR"
fi

KLAY_PROCESSES="$KLAY_HOME/processes"

PROCESSES_DIR="$KLAY_HOME/processes.d"
if ! [ -d "$PROCESSES_DIR" ]; then
  mkdir -p "$PROCESSES_DIR"
fi

# TODO:
# $DEBUG_OPTS

SHELL_COMMANDS=('ps' 'stop')

if [[ ! " ${SHELL_COMMANDS[*]} " =~ " $1 " ]]; then
  source "$SCRIPTS_HOME/execw.sh" "$@"
else
  if [ "$1" == "ps" ]; then
    source "$SCRIPTS_HOME/kps.sh"
  elif [ "$1" == "stop" ]; then
    source "$SCRIPTS_HOME/kstop.sh" $2
  fi
fi
