#!/usr/bin/env bash

SCRIPTS_HOME=$(dirname "$0")

export KLAY_HOME="$HOME/.klay"
LOGS_DIR="$KLAY_HOME/logs"
if ! [ -d "$LOGS_DIR" ]; then
  mkdir -p "$LOGS_DIR"
fi

KLAY_PROCESSES="$KLAY_HOME/processes"

PROCESSES_DIR="$KLAY_HOME/processes.d"
if ! [ -d "$PROCESSES_DIR" ]; then
  mkdir -p "$PROCESSES_DIR"
fi

# TODO:
# $DEBUG_OPTS

SHELL_COMMANDS=('ps' 'stop' 'logs' 'describe' 'prune')

# Redirect execution to execw.sh when -h or --help, even when its a shell command
export KLAY_HELP_REQUESTED=$([[ "$2" == "-h" ]] || [[ "$2" == "--help" ]] && echo -n 'y' || echo -n 'n')

if [[ ! " ${SHELL_COMMANDS[*]} " =~ " $1 " ]] || [[ "$KLAY_HELP_REQUESTED" == "y" ]]; then
  source "$SCRIPTS_HOME/execw.sh" "$@"
else
  if [ "$1" == "ps" ]; then
    source "$SCRIPTS_HOME/kps.sh" $2
  elif [ "$1" == "stop" ]; then
    source "$SCRIPTS_HOME/kstop.sh" $2
  elif [ "$1" == "logs" ]; then
    source "$SCRIPTS_HOME/klogs.sh" "${@:2}"
  elif [ "$1" == "describe" ]; then
    source "$SCRIPTS_HOME/__describe.sh" "${@:1}"
  elif [ "$1" == "prune" ]; then
    source "$SCRIPTS_HOME/__prune.sh"
  fi
fi
